#!/bin/env python3

FRAMES_TILL_IMAGE_EXTRACTION = 30
AUG_RANDOM_ROTATION = 0.025
AUG_RANDOM_TRANSLATION_H = 0.1
AUG_RANDOM_TRANSLATION_W = 0.04
AUG_FILL_VALUE = 255
ROUGHLY_NBR_OF_FILES_PER_CLASS = 10_000
