#!/bin/env python3

from enum import Enum

import cv2

SIZE_FACTOR = 0.3
CRITICAL_DIST_FROM_OTHER_CENTER = 20
TARGET_SIZE = (24, 68)
COMPARED_SIZE = (TARGET_SIZE[1], TARGET_SIZE[0])
AREA_BORDER = TARGET_SIZE[0] * TARGET_SIZE[1]
WIDTH_TO_HEIGHT = TARGET_SIZE[0] / TARGET_SIZE[1]
MIN_WIDTH_TO_HEIGHT = WIDTH_TO_HEIGHT * (1 - SIZE_FACTOR)
MAX_WIDTH_TO_HEIGHT = WIDTH_TO_HEIGHT * (1 + SIZE_FACTOR)
BLUR_KERNEL = (3,3)
TERM_CRITERIA = (cv2.TERM_CRITERIA_EPS + cv2.TERM_CRITERIA_MAX_ITER, 30, 0.001)


class COLORS(Enum):
    RED = (0, 0, 255)
    BLUE = (255, 0, 0)
    GREEN = (0, 255, 0)
    PURPLE = (255, 0, 255)



